package:
  name: heimdali
  version: 0.6.3

source:
  path: ..
  #fn: heimdali-0.6.3.tar.gz
  #url: https://github.com/dfroger/heimdali/archive/0.6.3.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - tclap
    - itk-heimdali ==4.7.0.1
    - h5unixpipe
    - libinrimage
  run:
    - tclap
    - itk-heimdali ==4.7.0.1
    - h5unixpipe
    - libinrimage

test:
  commands:
    - par --help

about:
  home: https://github.com/dfroger/heimdali 
  license: GPL
