package:
  name: heimdali
  version: 0.0.0

source:
  fn: heimdali-0.0.0.tar.gz
  url: https://github.com/dfroger/heimdali/archive/0.0.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - tclap
    - itk
    - h5unixpipe
    - libinrimage
  run:
    - tclap
    - itk
    - h5unixpipe
    - libinrimage

test:
  commands:
    - par --help

about:
  home: https://github.com/dfroger/heimdali 
  license: GPL
