package:
  name: heimdali
  version: 0.7.0

source:
  path: ..
  #fn: heimdali-0.7.0.tar.gz
  #url: https://github.com/dfroger/heimdali/archive/0.7.0.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - cmake
    - tclap
    - itk-heimdali ==4.7.0.1
    - h5unixpipe
    - libinrimage ==4.6.6
  run:
    - tclap
    - itk-heimdali ==4.7.0.1
    - h5unixpipe
    - libinrimage ==4.6.6

test:
  commands:
    - par --help

about:
  home: https://github.com/dfroger/heimdali 
  license: GPL
